# This workflow will build and push vitpress
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '22'
  PNPM_VERSION: '9'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: ${{ env.PNPM_VERSION }}
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: pnpm install, build
      run: |
        pnpm install
        pnpm docs:build
